import { Flex } from '@chakra-ui/react';
import Head from 'next/head';
import Login from './components/Login';

export default function Home() {
  return (
    <Flex height="100vh" alignItems="center" justifyContent="center">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Login />
    </Flex>
  );
}
